---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-7.4

suites:
  - name: package
    run_list:
      - recipe[oversip]
    attributes: {

    }
  # - name: tarball
  #   run_list:
  #     - recipe[oversip]
  #   attributes: {
  #     oversip: {
  #       install_method: 'tarball'
  #     }
  #   }